### ISSUE TITLE
Failing to use with simple example/plain text responses

### ISSUE THREAD

**Issue by gjb1002** [znsio/specmatic#848] opened 2023-12-07 14:33 UTC
Just downloaded Specmatic and tried to get it working on a super-simple microservices example I've used with other tools. But two things so far didn't work as expected:

1. It didn't like my openapi.json file, I had to convert it to yaml before I could do anything. Are there any plans to support the json format also, as many tools (such as Python flask which is my example technology) make this format the default?
2. My endpoint returns plain text, and the openapi spec clearly says that it will do this. Specmatic however, wanted json responses anyway and failed with:
Contract expected JSON object but response contained "Hello, GMUOS!" 

```
    responses:
        '200':
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/Generated'
          description: Successful response
```
I realise not many real applications expect plain text, but shouldn't it be allowed? It seems like Specmatic is ignoring this aspect of the spec.

Response at 2023-12-7 3:31:6.739
    200 OK
    Server: Werkzeug/2.3.7 Python/3.10.6
    Date: Thu, 07 Dec 2023 14:31:06 GMT
    Content-Type: text/html; charset=utf-8
    Content-Length: 13
    Access-Control-Allow-Origin: *
    Connection: close

    Hello, GMUOS!

**Comment by joelrosario** [comment] 2023-12-08 07:02
Hi @gjb1002,

I wasn't able to replicate this issue. I've tested using the following sample specification:

```yaml
openapi: 3.0.0
info:
  title: Text/HTML API
  version: 1.0.0
paths:
  /api:
    post:
      summary: Create a text/html response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        '200':
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/Generated'
          description: Successful response
components:
  schemas:
    Generated:
      type: string
      example: '<html><body><h1>Hello, world!</h1></body></html>'
```

And I used the following commands:

```bash
#!/bin/bash

java -jar specmatic.jar stub --noConsoleLog --textLog ./specmatic_stub_log txthtml.yaml &
stub_pid=$!

sleep 3

java -jar specmatic.jar test txthtml.yaml

kill $stub_pid
```

I'm using [Specmatic 1.0.3](https://github.com/znsio/specmatic/releases/tag/1.0.3).

Could you tell me more about
1. the specification you're using that results in the error you're seeing, even provide the specification if possible which I can use to replicate the issue locally
2. how you are executing the test (are you using the command or running it from SpecmaticJUnitSupport)

Thanks.

**Comment by gjb1002** [comment] 2023-12-08 08:18
I'm just trying to run the simplest thing possible, i.e. your "get started in 5 minutes" instructions, just using my simple Python example rather than yours. So I'm not doing any stub commands, just

specmatic test --testBaseURL=http://127.0.0.1:5010 openapi.yaml

The spec you're using looks much the same as mine.

Unfortunately, I changed my example to use json in order to make progress and didn't save the state of it before that. I now tried to put it back how it was before but it seems to work for me now - so I don't know what I was doing differently yesterday.

I'm also interested in my first question, i.e. whether there are any plans to support openapi.json files directly.

**Comment by harikrishnan83** [comment] 2023-12-08 10:21
@gjb1002 Good to know you have got it to work. However, we will also continue to test on our side to see if we are able to reproduce the issue.

About the support json OpenAPI files, in our experience the preference for authoring OpenAPI specifications has been YAML because of the readability and so even we had maintained file extension check for the same. However adding support for the same is trivial (we have already pushed some commits in this regard as you can see above) and will be part of our upcoming releases.

Thanks again for reaching out.

**Comment by gjb1002** [comment] 2023-12-08 10:55
@harikrishnan83 OK, thanks. It surprises me what you write about YAML readability, as both the frameworks I'm familiar with (Swashbuckle and FlaskAPI) use json by default, so the applications I know using them also do this. 

But good that you're adding stuff to support this! Nice not to force people to change their default setup on adopting a test tool.

**Closed as completed** 2023-12-11 12:41 UTC
Labels: question
